[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

# Fix caching and date issues
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Specific headers for HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Headers for static assets (JS, CSS, images)
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/jobs/*"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/category/*"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/location/*"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/companies"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200